
package hi.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Tue Jan 02 16:30:12 IST 2018
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "hi", namespace = "http://hi/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hi", namespace = "http://hi/")

public class Hi {


}

