
package com.gdg.rocky.classes.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Dec 15 09:00:47 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "myString", namespace = "http://classes.rocky.gdg.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "myString", namespace = "http://classes.rocky.gdg.com/")

public class MyString {


}

