
package controller.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Tue Jan 02 14:20:49 IST 2018
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "findAllCampusMindResponse", namespace = "http://controller/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllCampusMindResponse", namespace = "http://controller/")

public class FindAllCampusMindResponse {

    @XmlElement(name = "return")
    private java.util.List<entities.CampusMind> _return;

    public java.util.List<entities.CampusMind> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<entities.CampusMind> new_return)  {
        this._return = new_return;
    }

}

